"""
Pydantic models for structured data throughout the application.
Defines schemas for plans, tool results, and agent outputs.
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Any, Dict
from enum import Enum
from datetime import datetime


class ToolType(str, Enum):
    """Available tool types in the system."""
    GITHUB = "github"
    WEATHER = "weather"


class StepStatus(str, Enum):
    """Execution status of a plan step."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    RETRYING = "retrying"


class PlanStep(BaseModel):
    """A single step in the execution plan."""
    step_number: int = Field(..., description="Sequential step number")
    description: str = Field(..., description="What this step accomplishes")
    tool: ToolType = Field(..., description="Tool to use for this step")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Parameters for the tool")
    depends_on: List[int] = Field(default_factory=list, description="Step numbers this depends on")


class ExecutionPlan(BaseModel):
    """Complete execution plan generated by the Planner agent."""
    task_summary: str = Field(..., description="Brief summary of the user's task")
    steps: List[PlanStep] = Field(..., description="Ordered list of execution steps")
    reasoning: str = Field(..., description="Explanation of why this plan was chosen")


class ToolResult(BaseModel):
    """Result from a tool execution."""
    tool: ToolType
    success: bool
    data: Optional[Any] = None
    error: Optional[str] = None
    execution_time_ms: float = 0
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class StepResult(BaseModel):
    """Result of executing a single plan step."""
    step_number: int
    status: StepStatus
    tool_result: Optional[ToolResult] = None
    retry_count: int = 0
    error_message: Optional[str] = None


class ExecutionResult(BaseModel):
    """Complete result from the Executor agent."""
    plan: ExecutionPlan
    step_results: List[StepResult]
    total_execution_time_ms: float
    success: bool
    partial_success: bool = False


class VerificationResult(BaseModel):
    """Result from the Verifier agent."""
    is_valid: bool
    completeness_score: float = Field(..., ge=0.0, le=1.0)
    issues: List[str] = Field(default_factory=list)
    suggestions: List[str] = Field(default_factory=list)
    final_output: Dict[str, Any] = Field(default_factory=dict)
    formatted_response: str = ""


class AgentResponse(BaseModel):
    """Final response from the AI Operations Assistant."""
    task: str
    plan: ExecutionPlan
    execution: ExecutionResult
    verification: VerificationResult
    total_time_ms: float
    success: bool


class GitHubRepository(BaseModel):
    """GitHub repository information."""
    name: str
    full_name: str
    description: Optional[str] = None
    stars: int = Field(..., alias="stargazers_count")
    forks: int = Field(..., alias="forks_count")
    language: Optional[str] = None
    url: str = Field(..., alias="html_url")
    
    class Config:
        populate_by_name = True


class WeatherData(BaseModel):
    """Weather information for a location."""
    city: str
    country: str
    temperature_celsius: float
    temperature_fahrenheit: float
    feels_like_celsius: float
    humidity: int
    description: str
    wind_speed_mps: float
    visibility_km: float
    timestamp: datetime = Field(default_factory=datetime.utcnow)
